#ifndef MDALARMLEVELCONFIGER_GLOBAL_H
#define MDALARMLEVELCONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDALARMLEVELCONFIGER_LIBRARY)
#  define MDALARMLEVELCONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDALARMLEVELCONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDALARMLEVELCONFIGER_GLOBAL_H
