#ifndef MDPOWERGROUPUI_GLOBAL_H
#define MDPOWERGROUPUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDPOWERGROUPUI_LIBRARY)
#  define MDPOWERGROUPUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDPOWERGROUPUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDPOWERGROUPUI_GLOBAL_H
