#ifndef MDALARMHELPER_GLOBAL_H
#define MDALARMHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDALARMHELPER_LIBRARY)
#  define MDALARMHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDALARMHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDALARMHELPER_GLOBAL_H
