#ifndef NCRDGLOBALS_H
#define NCRDGLOBALS_H

#include "info.h"

#ifdef PACOS_INTEGRATION
    #define REPORTDESIGNER_NAME_EXTENSION   " (PACOS)"
#else
    #define REPORTDESIGNER_NAME_EXTENSION   ""
#endif

#define REPORTDESIGNER_NAME		"Report Designer" REPORTDESIGNER_NAME_EXTENSION
#define REPORTDESIGNER_VERSION		NCREPORTAPP_VERSION
#define REPORTDESIGNER_RELEASENAME	NCREPORTAPP_RELEASENAME
#define REPORTDESIGNER_COPYRIGHT	NCREPORTAPP_COPYRIGHT

#define NCRDSETTINGS_ORG	NCREPORTAPP_ORG
#define NCRDSETTINGS_APP	"NCReportDesigner"

#if defined(DESIGNER_LIBRARY)
#  define NCREPORTDESIGNER_SHARED_EXPORT Q_DECL_EXPORT
#elif defined(DESIGNER_IMPORT)
#  define NCREPORTDESIGNER_SHARED_EXPORT Q_DECL_IMPORT
#else
#  define NCREPORTDESIGNER_SHARED_EXPORT
#endif

#endif
