#ifndef MDEVENTACTIONUI_GLOBAL_H
#define MDEVENTACTIONUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDEVENTACTIONUI_LIBRARY)
#  define MDEVENTACTIONUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDEVENTACTIONUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDEVENTACTIONUI_GLOBAL_H
