#include "HMIConfigData.h"

/*
id：类型
text：文本
imagePath:图标目录
item:实际控件
type：控件类型，参考DrawObjDefine
image:图标文件
notInToolkit:不在工具箱中显示
*/
const QString CHMIConfigData::DrawObject = R"(
[
    {
        "id": "Multi",
        "imagePath":":/rs/image/",
        "notInToolkit":true,
        "items":
        [
            {
                "id":"Group",
                "type":0,
                "image":"group.png"
            },
            {
                "id":"Combine",
                "type":1,
                "image":"combine.png"
            }
        ]
    },
    {
        "id": "Vector",
        "text": "矢量",
        "imagePath":":/rs/image/draw/",
        "items":
        [
            {
                "id":"Rect",
                "type":2,
                "text":"矩形",
                "image":"Rect.png"
            },
            {
                "id":"Ellipse",
                "type":3,
                "text":"圆形",
                "image":"Ellipse.png"
            },
            {
                "id":"Arc",
                "type":4,
                "text":"圆弧",
                "image":"Arc.png"
            },
            {
                "id":"Sector",
                "type":5,
                "text":"扇形",
                "image":"Sector.png"
            },
            {
                "id":"Shear",
                "type":6,
                "text":"圆切",
                "image":"Shear.png"
            },
            {
                "id":"Text",
                "type":7,
                "text":"文本",
                "image":"Text.png"
            },
            {
                "id":"Button",
                "type":8,
                "text":"按钮",
                "image":"button.png"
            }
        ]
    },
    {
        "id": "Line",
        "text": "线和管道",
        "imagePath":":/rs/image/draw/",
        "items":
        [
            {
                "id":"StraightLine",
                "type":9,
                "text":"直线",
                "image":"StraightLine.png"
            },
            {
                "id":"FoldLine",
                "type":10,
                "text":"折线",
                "image":"FoldLine.png"
            },
            {
                "id":"Bezier",
                "type":11,
                "text":"曲线",
                "image":"Bezier.png"
            },
            {
                "id":"Polygon",
                "type":12,
                "text":"多边形",
                "image":"Polygon.png"
            },
            {
                "id":"ClosedBezier",
                "type":13,
                "text":"曲线多边形",
                "image":"ClosedBezier.png"
            },
            {
                "id":"Pipe",
                "type":27,
                "text":"流动管道",
                "image":"pipe.png"
            }
        ]
    },
    {
        "id": "Widget",
        "text": "窗体",
        "imagePath":":/rs/image/draw/",
        "items":
        [
            {
                "id":"TextEdit",
                "type":14,
                "text":"编辑框",
                "image":"TextEdit.png"
            },
            {
                "id":"ComboBox",
                "type":15,
                "text":"下拉框",
                "image":"ComboBox.png"
            },
            {
                "id":"List",
                "type":16,
                "text":"列表",
                "image":"List.png"
            },
            {
                "id":"RadioButton",
                "type":17,
                "text":"单选按钮",
                "image":"Radio.png"
            },
            {
                "id":"CheckBox",
                "type":18,
                "text":"复选按钮",
                "image":"CheckBox.png"
            },
            {
                "id":"SpinBox",
                "type":19,
                "text":"微调按钮",
                "image":"Spin.png"
            },
            {
                "id":"DateTime",
                "type":20,
                "text":"时间",
                "image":"Time.png"
            },
            {
                "id":"Calendar",
                "type":21,
                "text":"日期",
                "image":"Date.png"
            }
        ]
    },
    {
        "id": "Special",
        "text": "特殊",
        "imagePath":":/rs/image/draw/",
        "items":
        [
            {
                "id":"Alarm",
                "type":22,
                "text":"报警",
                "image":"alarm.png"
            },
            {
                "id":"Log",
                "type":23,
                "text":"日志",
                "image":"Log.png"
            },
            {
                "id":"DataArchives",
                "type":28,
                "text":"数据归档",
                "image":"DataArchives.png"
            },
            {
                "id":"Gauge",
                "type":24,
                "text":"表盘",
                "image":"gauge.png"
            },
            {
                "id":"RealCurve",
                "type":25,
                "text":"实时曲线",
                "image":"RealCurve.png"
            },
            {
                "id":"HistoryCurve",
                "type":30,
                "text":"历史曲线",
                "image":"HisCurve.png"
            },
            {
                "id":"Report",
                "type":26,
                "text":"报表",
                "image":"report.png"
            },
            {
                "id":"Diagram",
                "type":29,
                "text":"统计图",
                "image":"Diagram.png"
            },
            {
                "id":"RecipeGrid",
                "type":32,
                "text":"配方",
                "image":"RecipeGrid.png"
            },
            {
               "id":"ProcDocker",
               "type":33,
               "text":"进程容器",
               "image":"ProcDocker.png"
            },
            {
                "id":"PdfViewer",
                "type":34,
                "text":"Pdf阅读器",
                "image":"PdfViewer.png"
            }
        ]
    }
]
)";
