#ifndef MDRECIPEHELPER_GLOBAL_H
#define MDRECIPEHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDRECIPEHELPER_LIBRARY)
#  define MDRECIPEHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDRECIPEHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDRECIPEHELPER_GLOBAL_H
