#ifndef MDEVENTCONFIGER_GLOBAL_H
#define MDEVENTCONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDEVENTCONFIGER_LIBRARY)
#  define MDEVENTCONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDEVENTCONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDEVENTCONFIGER_GLOBAL_H
