#ifndef MDOBJECTMANAGERUI_GLOBAL_H
#define MDOBJECTMANAGERUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDOBJECTMANAGERUI_LIBRARY)
#  define MDOBJECTMANAGERUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDOBJECTMANAGERUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDOBJECTMANAGERUI_GLOBAL_H
