#ifndef MDRTDBMANAGERUI_GLOBAL_H
#define MDRTDBMANAGERUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDRTDBMANAGERUI_LIBRARY)
#  define MDRTDBMANAGERUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDRTDBMANAGERUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDRTDBMANAGERUI_GLOBAL_H
