#ifndef DATAARCHIVETESTORPLUGIN_GLOBAL_H
#define DATAARCHIVETESTORPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DATAARCHIVETESTORPLUGIN_LIBRARY)
#  define DATAARCHIVETESTORPLUGIMDHARED_EXPORT Q_DECL_EXPORT
#else
#  define DATAARCHIVETESTORPLUGIMDHARED_EXPORT Q_DECL_IMPORT
#endif

//TODO:删除此文件

#endif // DATAARCHIVETESTORPLUGIN_GLOBAL_H
