#ifndef MDALARMCONDITIONCONFIGER_GLOBAL_H
#define MDALARMCONDITIONCONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDALARMCONDITIONCONFIGER_LIBRARY)
#  define MDALARMCONDITIONCONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDALARMCONDITIONCONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDALARMCONDITIONCONFIGER_GLOBAL_H
