#ifndef MDPROJECTHELPER_GLOBAL_H
#define MDPROJECTHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDPROJECTHELPER_LIBRARY)
#  define MDPROJECTHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDPROJECTHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDPROJECTHELPER_GLOBAL_H
