#ifndef MDCOMMANDQUEUEENGINE_GLOBAL_H
#define MDCOMMANDQUEUEENGINE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDCOMMANDQUEUEENGINE_LIBRARY)
#  define MDCOMMANDQUEUEENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDCOMMANDQUEUEENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDCOMMANDQUEUEENGINE_GLOBAL_H
