#ifndef MDALARMLEVELUI_GLOBAL_H
#define MDALARMLEVELUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDALARMLEVELUI_LIBRARY)
#  define MDALARMLEVELUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDALARMLEVELUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDALARMLEVELUI_GLOBAL_H
