#ifndef MDACCOUNTSTRATEGYCONFIGER_GLOBAL_H
#define MDACCOUNTSTRATEGYCONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDACCOUNTSTRATEGYCONFIGER_LIBRARY)
#  define MDACCOUNTSTRATEGYCONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDACCOUNTSTRATEGYCONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDACCOUNTSTRATEGYCONFIGER_GLOBAL_H
