#ifndef MDCOMMANDQUEUEENGINEUI_GLOBAL_H
#define MDCOMMANDQUEUEENGINEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDCOMMANDQUEUEENGINEUI_LIBRARY)
#  define MDCOMMANDQUEUEENGINEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDCOMMANDQUEUEENGINEUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDCOMMANDQUEUEENGINEUI_GLOBAL_H
