#ifndef MDDATASELECTUI_GLOBAL_H
#define MDDATASELECTUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDDATASELECTUI_LIBRARY)
#  define MDDATASELECTUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDDATASELECTUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDDATASELECTUI_GLOBAL_H
