#ifndef MDSECURITYPOLICYUI_GLOBAL_H
#define MDSECURITYPOLICYUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDSECURITYPOLICYUI_LIBRARY)
#  define MDSECURITYPOLICYUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDSECURITYPOLICYUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDSECURITYPOLICYUI_GLOBAL_H
