#ifndef MDALARMEXPERT_GLOBAL_H
#define MDALARMEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDALARMEXPERT_LIBRARY)
#  define MDALARMEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDALARMEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDALARMEXPERT_GLOBAL_H
