#ifndef MDACTIONHELPER_GLOBAL_H
#define MDACTIONHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDACTIONHELPER_LIBRARY)
#  define MDACTIONHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDACTIONHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDACTIONHELPER_GLOBAL_H
