#ifndef MDDBQUERYEXPERT_GLOBAL_H
#define MDDBQUERYEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(DBQUERYSERVICE_LIBRARY)
#  define MDDBQUERYEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDDBQUERYEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDDBQUERYEXPERT_GLOBAL_H
