#ifndef MDALARMCONDITIONUI_GLOBAL_H
#define MDALARMCONDITIONUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDALARMCONDITIONUI_LIBRARY)
#  define MDALARMCONDITIONUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDALARMCONDITIONUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDALARMCONDITIONUI_GLOBAL_H
