#ifndef MDEVENTHELPER_GLOBAL_H
#define MDEVENTHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDEVENTHELPER_LIBRARY)
#  define MDEVENTHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDEVENTHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDEVENTHELPER_GLOBAL_H
