#ifndef MDPROJECTEXPERT_GLOBAL_H
#define MDPROJECTEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDPROJECTEXPERT_LIBRARY)
#  define MDPROJECTEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDPROJECTEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif


#endif // MDPROJECTEXPERT_GLOBAL_H
