#ifndef MDVARIABLECONFIGER_GLOBAL_H
#define MDVARIABLECONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDVARIABLECONFIGER_LIBRARY)
#  define MDVARIABLECONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDVARIABLECONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDVARIABLECONFIGER_GLOBAL_H
