#ifndef MDVARIABLEARCHIVES_GLOBAL_H
#define MDVARIABLEARCHIVES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDVARIABLEARCHIVES_LIBRARY)
#  define MDVARIABLEARCHIVESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDVARIABLEARCHIVESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDVARIABLEARCHIVES_GLOBAL_H
