#ifndef MDVARIABLEHELPER_GLOBAL_H
#define MDVARIABLEHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDVARIABLEHELPER_LIBRARY)
#  define MDVARIABLEHELPERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDVARIABLEHELPERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDVARIABLEHELPER_GLOBAL_H
