#ifndef MDRECIPEUI_GLOBAL_H
#define MDRECIPEUI_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDRECIPEUI_LIBRARY)
#  define MDRECIPEUISHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDRECIPEUISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDRECIPEUI_GLOBAL_H
