#ifndef MDDRIVERLIBS_GLOBAL_H
#define MDDRIVERLIBS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDDRIVERLIBS_LIBRARY)
#  define MDDRIVERLIBSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDDRIVERLIBSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDDRIVERLIBS_GLOBAL_H
