#ifndef MDSINGLEAPPLICATION_GLOBAL_H
#define MDSINGLEAPPLICATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDSINGLEAPPLICATION_LIBRARY)
#  define MDSINGLEAPPLICATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDSINGLEAPPLICATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDSINGLEAPPLICATION_GLOBAL_H
