#ifndef MDEVENTEXPERT_GLOBAL_H
#define MDEVENTEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDEVENTEXPERT_LIBRARY)
#  define MDEVENTEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDEVENTEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDEVENTEXPERT_GLOBAL_H
