#ifndef MDRECIPEEXPERT_GLOBAL_H
#define MDRECIPEEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDRECIPEEXPERT_LIBRARY)
#  define MDRECIPEEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDRECIPEEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDRECIPEEXPERT_GLOBAL_H
