#ifndef MDHISTORYEXPERT_GLOBAL_H
#define MDHISTORYEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDHISTORYEXPERT_LIBRARY)
#  define MDHISTORYEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDHISTORYEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDHISTORYEXPERT_GLOBAL_H
