#ifndef MDDATAARCHIVESENGINE_GLOBAL_H
#define MDDATAARCHIVESENGINE_GLOBAL_H

/*!

\author luyj

\section 功能
1.MDDATAARCHIVESENGINESHARED_EXPORT宏定义。

*/

#include <QtCore/qglobal.h>

#if defined(MDDATAARCHIVESENGINE_LIBRARY)
#  define MDDATAARCHIVESENGINESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDDATAARCHIVESENGINESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDDATAARCHIVESENGINE_GLOBAL_H
