#ifndef MDSWITCHFACTORY_GLOBAL_H
#define MDSWITCHFACTORY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDSWITCHFACTORY_LIBRARY)
#  define MDSWITCHFACTORYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDSWITCHFACTORYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDSWITCHFACTORY_GLOBAL_H
