#ifndef MDDEVICECLOUDEXPERT_GLOBAL_H
#define MDDEVICECLOUDEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDDEVICECLOUDEXPERT_LIBRARY)
#  define MDDEVICECLOUDEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDDEVICECLOUDEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDDEVICECLOUDEXPERT_GLOBAL_H
