#ifndef COMMUNICATIONLIBS_GLOBAL_H
#define COMMUNICATIONLIBS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMUNICATIONLIBS_LIBRARY)
#  define COMMUNICATIONLIBSSHARED_EXPORT Q_DECL_IMPORT
#else
#  define COMMUNICATIONLIBSSHARED_EXPORT Q_DECL_EXPORT
#endif

#endif // COMMUNICATIONLIBS_GLOBAL_H
