#ifndef MDACTIONEXPERT_GLOBAL_H
#define MDACTIONEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDACTIONEXPERT_LIBRARY)
#  define MDACTIONEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDACTIONEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDACTIONEXPERT_GLOBAL_H
