#ifndef MDSECURITYPOLICYCONFIGER_GLOBAL_H
#define MDSECURITYPOLICYCONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDSECURITYPOLICYCONFIGER_LIBRARY)
#  define MDSECURITYPOLICYCONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDSECURITYPOLICYCONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDSECURITYPOLICYCONFIGER_GLOBAL_H
