#ifndef MDRTDBMANAGER_GLOBAL_H
#define MDRTDBMANAGER_GLOBAL_H

#include <QtCore/qglobal.h>


#if defined(MDRTDBMANAGER_LIBRARY)
#  define MDRTDBMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDRTDBMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDRTDBMANAGER_GLOBAL_H
