#ifndef MDACCOUNTCONFIGER_GLOBAL_H
#define MDACCOUNTCONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDACCOUNTCONFIGER_LIBRARY)
#  define MDACCOUNTCONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDACCOUNTCONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDACCOUNTCONFIGER_GLOBAL_H
