#ifndef MDSCRIPTEXPERT_GLOBAL_H
#define MDSCRIPTEXPERT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDSCRIPTEXPERT_LIBRARY)
#  define MDSCRIPTEXPERTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDSCRIPTEXPERTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDSCRIPTEXPERT_GLOBAL_H
