#ifndef MDRECIPECONFIGER_GLOBAL_H
#define MDRECIPECONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDRECIPECONFIGER_LIBRARY)
#  define MDRECIPECONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDRECIPECONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDRECIPECONFIGER_GLOBAL_H
