#ifndef MDPROJECTREMOTECONFIGER_GLOBAL_H
#define MDPROJECTREMOTECONFIGER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MDPROJECTREMOTECONFIGER_LIBRARY)
#  define MDPROJECTREMOTECONFIGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MDPROJECTREMOTECONFIGERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MDPROJECTREMOTECONFIGER_GLOBAL_H
