#ifndef QSERIALPORT_GLOBAL_H
#define QSERIALPORT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSERIALPORT_LIBRARY)
#  define QSERIALPORTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QSERIALPORTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QSERIALPORT_GLOBAL_H
