#ifndef MDDB_COMMON_DEF_H_2017_2_8
#define MDDB_COMMON_DEF_H_2017_2_8

//数据库类型
enum DBSOURCE_TYPE
{
    DBSOURCE_TYPE_UNKNOWN = 0,
    DBSOURCE_TYPE_MYSQL,
    DBSOURCE_TYPE_SQL_SERVER,
    DBSOURCE_TYPE_ORACLE,
    DBSOURCE_TYPE_KINGBASE //金仓数据库
};

#endif //MDDB_COMMON_DEF_H_2017_2_8
